version: 2
# Reference variables.
references:
  docker_default: &docker_12
    working_directory: /tmp/app
    docker:
      - image: node:12
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"

jobs:
  build-node-12:
    <<: *docker_12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-12-cache-{{checksum "yarn.lock"}}
            - node-12-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn
            cd website && yarn
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: node-12-cache-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - website/node_modules
            - lib

  test-node-12:
    <<: *docker_12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: yarn testonly:cov -- --no-cache --colors
      - store_artifacts:
          path: coverage

  lint-node-12:
    <<: *docker_12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run lint:ts
          command: yarn lint:ts --report-unused-disable-directives
      - run:
          name: run lint:css
          command: yarn lint:css

  release:
    <<: *docker_12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run release
          command: yarn semantic-release

workflows:
  version: 2
  test-on-node-12:
    jobs:
      - build-node-12
      - test-node-12:
          requires:
            - build-node-12
      - lint-node-12:
          requires:
            - build-node-12
      - release:
          requires:
            - test-node-12
            - lint-node-12
