version: 2
# Reference variables.
references:
  docker_default: &docker_14
    working_directory: /tmp/app
    docker:
      - image: cimg/node:14.17
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"

jobs:
  build-node-14:
    <<: *docker_14
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-14-cache-{{checksum "yarn.lock"}}
            - node-14-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: node-14-cache-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - lib

  test-node-14:
    <<: *docker_14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: yarn testonly:cov -- --no-cache --colors
      - store_artifacts:
          path: coverage

  lint-node-14:
    <<: *docker_14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run lint
          command: yarn lint

  release:
    <<: *docker_14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run release
          command: yarn semantic-release

workflows:
  version: 2
  test-on-node-14:
    jobs:
      - build-node-14
      - test-node-14:
          requires:
            - build-node-14
      - lint-node-14:
          requires:
            - build-node-14
      - release:
          requires:
            - test-node-14
            - lint-node-14
