import {
  Alert,
  Box,
  Button,
  Card,
  Checkbox,
  Dropdown,
  Flex,
  FormField,
  Heading,
  Hint,
  Icon,
  Input,
  Label,
  Menu,
  Modal,
  Popconfirm,
  Popover,
  Radio,
  RadioField,
  Select,
  Space,
  Spin,
  Steps,
  Switch,
  Table,
  Tabs,
  TextField,
  Textarea,
  ThemeProvider,
  Tooltip,
  colors,
  injectGlobalCss,
  message,
} from '..';

describe('index', () => {
  it('should export all components', () => {
    expect(Alert).toBeDefined();
    expect(Box).toBeDefined();
    expect(Button).toBeDefined();
    expect(Card).toBeDefined();
    expect(Checkbox).toBeDefined();
    expect(Checkbox.Group).toBeDefined();
    expect(Dropdown).toBeDefined();
    expect(Flex).toBeDefined();
    expect(FormField).toBeDefined();
    expect(Heading).toBeDefined();
    expect(Hint).toBeDefined();
    expect(Icon).toBeDefined();
    expect(Input).toBeDefined();
    expect(Label).toBeDefined();
    expect(Menu).toBeDefined();
    expect(message).toBeDefined();
    expect(Modal).toBeDefined();
    expect(Popconfirm).toBeDefined();
    expect(Popover).toBeDefined();
    expect(Radio).toBeDefined();
    expect(RadioField).toBeDefined();
    expect(Select).toBeDefined();
    expect(Space).toBeDefined();
    expect(Spin).toBeDefined();
    expect(Steps).toBeDefined();
    expect(Switch).toBeDefined();
    expect(Table).toBeDefined();
    expect(Tabs).toBeDefined();
    expect(Textarea).toBeDefined();
    expect(TextField).toBeDefined();
    expect(ThemeProvider).toBeDefined();
    expect(Tooltip).toBeDefined();
    expect(colors).toBeDefined();
    expect(injectGlobalCss).toBeDefined();
  });
});
