import {
  Alert,
  Box,
  Button,
  Card,
  Checkbox,
  DatePicker,
  Divider,
  Dropdown,
  Flex,
  FormField,
  Heading,
  Hint,
  Icon,
  Input,
  Label,
  Mention,
  Menu,
  Modal,
  Popconfirm,
  Popover,
  Radio,
  Select,
  Space,
  Spin,
  Steps,
  Switch,
  Table,
  Tabs,
  Tag,
  TextField,
  Textarea,
  Tooltip,
  UIProvider,
  Upload,
  message,
  theme,
} from '..';

describe('index', () => {
  it('should export all components', () => {
    expect(Alert).toBeDefined();
    expect(Box).toBeDefined();
    expect(Button).toBeDefined();
    expect(Card).toBeDefined();
    expect(Checkbox).toBeDefined();
    expect(Checkbox.Group).toBeDefined();
    expect(DatePicker).toBeDefined();
    expect(Divider).toBeDefined();
    expect(Dropdown).toBeDefined();
    expect(Flex).toBeDefined();
    expect(FormField).toBeDefined();
    expect(Heading).toBeDefined();
    expect(Hint).toBeDefined();
    expect(Icon).toBeDefined();
    expect(Input).toBeDefined();
    expect(Label).toBeDefined();
    expect(Menu).toBeDefined();
    expect(Mention).toBeDefined();
    expect(message).toBeDefined();
    expect(Modal).toBeDefined();
    expect(Popconfirm).toBeDefined();
    expect(Popover).toBeDefined();
    expect(Radio).toBeDefined();
    expect(Radio.Group).toBeDefined();
    expect(Select).toBeDefined();
    expect(Space).toBeDefined();
    expect(Spin).toBeDefined();
    expect(Steps).toBeDefined();
    expect(Switch).toBeDefined();
    expect(Table).toBeDefined();
    expect(Tabs).toBeDefined();
    expect(Tag).toBeDefined();
    expect(Textarea).toBeDefined();
    expect(TextField).toBeDefined();
    expect(Tooltip).toBeDefined();
    expect(theme).toBeDefined();
    expect(UIProvider).toBeDefined();
    expect(Upload).toBeDefined();
  });
});
