module.exports = {
  docs: {
    Overview: ['getting-started', 'colors'],
    General: ['button', 'icon', 'ui-provider'],
    Typography: ['typography/heading', 'typography/text'],
    Layout: [
      'layout/box',
      'layout/flex',
      'layout/grid',
      'layout/responsive',
      'layout/spacing-scale',
      'layout/width-scale',
    ],
    Navigation: ['breadcrumb', 'dropdown', 'menu', 'page-header', 'steps'],
    'Data Entry': [
      'checkbox',
      'date-picker',
      'form-field',
      'input',
      'mention',
      'radio',
      'slider',
      'select',
      'switch',
      'tel-input',
      'textfield',
      'upload',
    ],
    'Data Display': [
      'badge',
      'card',
      'container',
      'divider',
      'popover',
      'table',
      'tag',
      'tooltip',
    ],
    Feedback: ['alert', 'drawer', 'modal', 'message', 'popconfirm', 'spin'],
    Formik: [
      'formik/input-field',
      'formik/textarea-field',
      'formik/checkbox-field',
      'formik/radio-field',
      'formik/select-field',
    ],
    Lab: ['lab/tabs', 'lab/select', 'lab/tooltip'],
  },
};
