import {
  Alert,
  Box,
  Button,
  Card,
  Checkbox,
  DatePicker,
  Divider,
  Drawer,
  Flex,
  FormField,
  Heading,
  Icon,
  Input,
  Mention,
  Menu,
  Modal,
  Radio,
  Select,
  Spin,
  Steps,
  Switch,
  Table,
  Tabs,
  Tag,
  TelInput,
  TextField,
  Textarea,
  UIProvider,
  Upload,
  theme,
  useMessage,
  useModal,
} from '..';

describe('index', () => {
  it('should export all components', () => {
    expect(Alert).toBeDefined();
    expect(Box).toBeDefined();
    expect(Button).toBeDefined();
    expect(Card).toBeDefined();
    expect(Checkbox).toBeDefined();
    expect(Checkbox.Group).toBeDefined();
    expect(DatePicker).toBeDefined();
    expect(Divider).toBeDefined();
    expect(Drawer).toBeDefined();
    expect(Flex).toBeDefined();
    expect(FormField).toBeDefined();
    expect(Heading).toBeDefined();
    expect(Icon).toBeDefined();
    expect(Input).toBeDefined();
    expect(Mention).toBeDefined();
    expect(Menu).toBeDefined();
    expect(Modal).toBeDefined();
    expect(Radio).toBeDefined();
    expect(Radio.Group).toBeDefined();
    expect(Select).toBeDefined();
    expect(Spin).toBeDefined();
    expect(Steps).toBeDefined();
    expect(Switch).toBeDefined();
    expect(Table).toBeDefined();
    expect(Tabs).toBeDefined();
    expect(Tag).toBeDefined();
    expect(Textarea).toBeDefined();
    expect(TelInput).toBeDefined();
    expect(TextField).toBeDefined();
    expect(theme).toBeDefined();
    expect(UIProvider).toBeDefined();
    expect(Upload).toBeDefined();
    expect(useMessage).toBeDefined();
    expect(useModal).toBeDefined();
  });
});
